package com.espada.gui.wilayah;

import com.espada.model.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Kabupaten extends javax.swing.JFrame {
    qKabupaten kabupaten = new qKabupaten();
    qKecamatan kecamatan = new qKecamatan();
    qProvinsi provinsi = new qProvinsi();
    private int tempDelete=-1;
    private String[] provinsiArray = new String[provinsi.getProvinsi().size()];
    /**
     * Creates new form Kabupaten
     */
    public Kabupaten() {
        initComponents();
        this.setTitle("Kabupaten Setting");
        this.setLocationRelativeTo(null);
        ImageIcon ico = new ImageIcon("logo.png");
        this.setIconImage(ico.getImage());
        fillProvinsiCombo();
        fillKabupaten();
    }
    
    public void fillProvinsiCombo(){
        comboProvinsi.removeAllItems();
        for(int i=0;i<provinsi.getProvinsi().size();i++){
            provinsiArray[i]=(String)provinsi.getProvinsi().get(i).get(1);
            comboProvinsi.addItem((String)provinsi.getProvinsi().get(i).get(0));
        }
    }
    
    public void fillKabupaten(){
        
        DefaultTableModel model = (DefaultTableModel) tableKabupaten.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        for(int i=0;i<kabupaten.getKota().size();i++){
            model.addRow(new Object[]{kabupaten.getKota().get(i).get(0), kabupaten.getKota().get(i).get(2), provinsi.getProvinsi((String) kabupaten.getKota().get(i).get(1)).get(0).get(0)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableKabupaten = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelKabupaten = new javax.swing.JLabel();
        textKabupaten = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        labelViewKabupaten = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        comboProvinsi = new javax.swing.JComboBox<String>();
        labelProvinsi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tableKabupaten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Kabupaten / Kota", "Provinsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKabupaten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKabupatenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKabupaten);
        if (tableKabupaten.getColumnModel().getColumnCount() > 0) {
            tableKabupaten.getColumnModel().getColumn(0).setMinWidth(30);
            tableKabupaten.getColumnModel().getColumn(0).setMaxWidth(30);
            tableKabupaten.getColumnModel().getColumn(1).setResizable(false);
            tableKabupaten.getColumnModel().getColumn(2).setResizable(false);
        }

        labelKabupaten.setText("Nama Kota/Kab:");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        labelViewKabupaten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewKabupaten.setText("Kabupaten");

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        comboProvinsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelProvinsi.setText("Provinsi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelViewKabupaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelKabupaten)
                            .addComponent(labelProvinsi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboProvinsi, 0, 213, Short.MAX_VALUE)
                            .addComponent(textKabupaten))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProvinsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKabupaten)
                    .addComponent(textKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(labelViewKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String idProvinsi = provinsiArray[comboProvinsi.getSelectedIndex()];
        if(kabupaten.setKota(textKabupaten.getText(), idProvinsi)==true){
        JOptionPane.showMessageDialog(this, "Kabupaten/Kota berhasil ditambahkan");
        }
        fillKabupaten();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tempDelete==-1){
            JOptionPane.showMessageDialog(this, "Pilih kabupaten/kota untuk menghapus");
        }else{
            if(
                    (kecamatan.getKecamatan(Integer.toString(tempDelete))==null)
                    ||
                    (kecamatan.getKecamatan(Integer.toString(tempDelete)).size()==0)
               ){
                if(kabupaten.deleteKota(tempDelete)){
                    JOptionPane.showMessageDialog(this, "Berhasil menghapus kabupaten/kota");
                }else{
                    JOptionPane.showMessageDialog(this, "Gagal menghapus kabupaten/kota");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Gagal menghapus kabupaten/kota, masih terdapat kecamatan di kabupaten yang dipilih");
            }
        }
        fillKabupaten();
        tempDelete=-1;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableKabupatenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKabupatenMouseClicked
        // TODO add your handling code here:
        tempDelete=Integer.parseInt((String)tableKabupaten.getValueAt(tableKabupaten.getSelectedRow(),0));
        labelViewKabupaten.setText((String) tableKabupaten.getValueAt(tableKabupaten.getSelectedRow(), 1));
    }//GEN-LAST:event_tableKabupatenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kabupaten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kabupaten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> comboProvinsi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKabupaten;
    private javax.swing.JLabel labelProvinsi;
    private javax.swing.JLabel labelViewKabupaten;
    private javax.swing.JTable tableKabupaten;
    private javax.swing.JTextField textKabupaten;
    // End of variables declaration//GEN-END:variables
}
