package com.espada.gui.wilayah;

import com.espada.model.qKabupaten;
import com.espada.model.qKecamatan;
import com.espada.model.qProvinsi;
import com.espada.model.qTarif;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Kecamatan extends javax.swing.JFrame {
    qKecamatan kecamatan = new qKecamatan();
    qKabupaten kabupaten = new qKabupaten();
    qProvinsi provinsi = new qProvinsi();
    qTarif tarif = new qTarif();
    private int tempDelete=-1;
    private String[] provinsiArray = new String[provinsi.getProvinsi().size()];
    private String[] kabupatenArray = new String[kabupaten.getKota().size()];
    /**
     * Creates new form Kecamatan
     */
    public Kecamatan() {
        initComponents();
        this.setTitle("Kecamatan Setting");
        this.setLocationRelativeTo(null);
        ImageIcon ico = new ImageIcon("logo.png");
        this.setIconImage(ico.getImage());
        fillKecamatan();
        fillProvinsiCombo();
        comboKabupaten.removeAllItems();
        comboKabupaten.enable(false);
    }
    
    public void fillKecamatan(){
         DefaultTableModel model = (DefaultTableModel) tableKecamatan.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        for(int i=0;i<kecamatan.getKecamatan().size();i++){
            String idKecamatan = (String) kecamatan.getKecamatan().get(i).get(0);
            String idKota = (String) kecamatan.getKecamatan().get(i).get(1);
            String namaKecamatan = (String) kecamatan.getKecamatan().get(i).get(2);
            String idProvinsi = (String) kabupaten.getKotaMe(idKota).get(0).get(1);
            String namaKota = (String) kabupaten.getKotaMe(idKota).get(0).get(2);
            String namaProvinsi = (String) provinsi.getProvinsiMe(idProvinsi).get(0).get(0);
            model.addRow(new Object[]{idKecamatan, namaKecamatan, namaProvinsi, namaKota});
        }
    }
    
    public void fillProvinsiCombo(){
        comboProvinsi.removeAllItems();
        for(int i=0;i<provinsi.getProvinsi().size();i++){
            provinsiArray[i]=(String)provinsi.getProvinsi().get(i).get(1);
            comboProvinsi.addItem((String)provinsi.getProvinsi().get(i).get(0));
        }
    }
    
    public void fillKabupatenCombo(String idProvinsi){
        comboKabupaten.removeAllItems();
        if(kabupaten.getKota(idProvinsi).size()<=0){
            comboKabupaten.enable(false);
        }else{
            comboKabupaten.enable(true);
            for(int i=0;i<kabupaten.getKota(idProvinsi).size();i++){
                kabupatenArray[i]=(String)kabupaten.getKota(idProvinsi).get(i).get(0);
                comboKabupaten.addItem((String)kabupaten.getKota(idProvinsi).get(i).get(2));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableKecamatan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelKecamatan = new javax.swing.JLabel();
        textKecamatan = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        labelViewKecamatan = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        comboProvinsi = new javax.swing.JComboBox<String>();
        labelProvinsi = new javax.swing.JLabel();
        comboKabupaten = new javax.swing.JComboBox<String>();
        labelKabupaten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tableKecamatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Kecamatan", "Provinsi", "Kabupaten / Kota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKecamatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKecamatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKecamatan);
        if (tableKecamatan.getColumnModel().getColumnCount() > 0) {
            tableKecamatan.getColumnModel().getColumn(0).setMinWidth(30);
            tableKecamatan.getColumnModel().getColumn(0).setMaxWidth(50);
            tableKecamatan.getColumnModel().getColumn(1).setResizable(false);
            tableKecamatan.getColumnModel().getColumn(2).setResizable(false);
            tableKecamatan.getColumnModel().getColumn(3).setResizable(false);
        }

        labelKecamatan.setText("Nama Kecamatan:");

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        labelViewKecamatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewKecamatan.setText("Kecamatan");

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        comboProvinsi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProvinsi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProvinsiItemStateChanged(evt);
            }
        });
        comboProvinsi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboProvinsiFocusLost(evt);
            }
        });

        labelProvinsi.setText("Provinsi:");

        comboKabupaten.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelKabupaten.setText("Kabupaten/Kota:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelViewKecamatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelKecamatan)
                            .addComponent(labelProvinsi)
                            .addComponent(labelKabupaten))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboProvinsi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textKecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(comboKabupaten, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProvinsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboKabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKabupaten))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKecamatan)
                    .addComponent(textKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(labelViewKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String idKota = (String) kabupatenArray[comboKabupaten.getSelectedIndex()];
        if(kecamatan.setKecamatan(textKecamatan.getText(), idKota)==true){
            JOptionPane.showMessageDialog(this, "Kecamatan berhasil ditambahkan");
        }
        fillKecamatan();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tempDelete==-1){
            JOptionPane.showMessageDialog(this, "Pilih kecamatan untuk menghapus");
        }else{
            if(tarif.checkKecamatan(Integer.toString(tempDelete))==false){
                if(kecamatan.deleteKecamatan(tempDelete)){
                    JOptionPane.showMessageDialog(this, "Berhasil menghapus Kecamatan");
                }else{
                    JOptionPane.showMessageDialog(this, "Gagal menghapus Kecamatan");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Kecamatan tidak dapat dihapus, kecamatan masih digunakan dalam tarif");
            }
        }
        fillKecamatan();
        tempDelete=-1;
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboProvinsiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboProvinsiFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboProvinsiFocusLost

    private void comboProvinsiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProvinsiItemStateChanged
        // TODO add your handling code here:
        int indexArray = comboProvinsi.getSelectedIndex();
        if(indexArray<0){   
            fillKabupatenCombo((String)provinsiArray[0]);
        }else{
            fillKabupatenCombo((String)provinsiArray[indexArray]);
        }
        
    }//GEN-LAST:event_comboProvinsiItemStateChanged

    private void tableKecamatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKecamatanMouseClicked
        // TODO add your handling code here:
        tempDelete=Integer.parseInt((String)tableKecamatan.getValueAt(tableKecamatan.getSelectedRow(),0));
        labelViewKecamatan.setText((String) tableKecamatan.getValueAt(tableKecamatan.getSelectedRow(), 1));
    }//GEN-LAST:event_tableKecamatanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kecamatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kecamatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kecamatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kecamatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kecamatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> comboKabupaten;
    private javax.swing.JComboBox<String> comboProvinsi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKabupaten;
    private javax.swing.JLabel labelKecamatan;
    private javax.swing.JLabel labelProvinsi;
    private javax.swing.JLabel labelViewKecamatan;
    private javax.swing.JTable tableKecamatan;
    private javax.swing.JTextField textKecamatan;
    // End of variables declaration//GEN-END:variables
}
