/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.espada.main;

import com.espada.Koneksi;
import com.espada.gui.Kasir;
import com.espada.gui.Login;
import com.espada.gui.SetDatabase;
import com.espada.gui.SetUsaha;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
/**
 *
 * @author Hafiizh Eko M
 */
public class Loading extends javax.swing.JFrame {
    private Koneksi kon = new Koneksi();
        
    
    public Loading() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2) - 200;
        this.setLocation(x, y);
        ImageIcon ico = new ImageIcon("logo.png");
        this.setIconImage(ico.getImage());
    }
    /**
     * Creates new form Load
     * @return 
     */
    
    public void openKasir(){
        Kasir windowKasir = new Kasir();
        windowKasir.pack();
        windowKasir.setVisible(true);
    }
    
    private boolean checkingUsaha(){
        //Checking Usaha
        try{
                Connection konektor = kon.Koneksi();
                Statement stat = konektor.createStatement();
                String query = "select * from ms_usaha";
                ResultSet usaha;
                usaha = stat.executeQuery(query);
                //Checking data usaha di ms_usaha
                    if(usaha.next()){
                        System.out.println("Informasi Usaha: OK!");
                        return true;
                    }else{
                        System.out.println("Informasi Usaha: Gagal Memuat");
                        SetUsaha windowUsaha = new SetUsaha();
                        windowUsaha.pack();
                        windowUsaha.setVisible(true);
                        return false;
                    }
            
        }catch(Exception e){
            System.out.println(e);
        }
        return false;
    }
    
    
    private boolean initialization(){
        try{
            //Checking database
                Connection konektor = kon.Koneksi();
                if(konektor == null){
                    System.out.println("Status Database: Gagal Memuat");
                    SetDatabase windowDatabase = new SetDatabase();
                    windowDatabase.pack();
                    windowDatabase.setVisible(true);
                    return false;
                }else{
                    System.out.println("Status Database: OK!");
                    if(this.checkingUsaha()){
                    return true;
                    }else{
                     return false;
                     
                    }
                }
        }catch(Exception e){
            
        }
        return false;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBanner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Espada - Loading");
        setUndecorated(true);

        labelBanner.setFont(new java.awt.Font("Goodbye Despair", 1, 72)); // NOI18N
        labelBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBanner.setText("ESPADA");

        jLabel1.setText("Version 1.0");

        jLabel2.setText("Ekspedisi Indonesia Djaja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBanner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Loading windowLoading = new Loading();
                windowLoading.pack();
                windowLoading.setVisible(true);
                if(windowLoading.initialization()==true){
                   Login windowLogin = new Login();
                   windowLogin.myLoader = windowLoading;
                   windowLogin.pack();
                   windowLogin.setVisible(true);
                   
                }
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBanner;
    // End of variables declaration//GEN-END:variables
}
