package com.espada.gui.excel.importz;

import com.espada.Excel;
import com.espada.model.qPengiriman;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pengiriman extends javax.swing.JFrame {
    private DefaultTableModel model;
    private String[][] hasilImport;
    private qPengiriman pengiriman = new qPengiriman();

    /**
     * Creates new form Pengiriman
     */
    public Pengiriman() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Pengiriman Import");
        ImageIcon ico = new ImageIcon("logo.png");
        this.setIconImage(ico.getImage());
        model= (DefaultTableModel) tablePengiriman.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImport = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePengiriman = new javax.swing.JTable();
        btnTemplate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnImport.setText("Import from Excel");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tablePengiriman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pengirim", "Nama Penerima", "ID Kec Pengirim", "ID Kec Penerima", "Alamat Penerima", "Tanggal Kirim", "Tanggal Tiba", "Total Berat", "ID Layanan", "ID Kurir", "Harga", "Hari", "Verifikasi", "Ket Barang", "Bobot Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePengiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePengirimanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePengiriman);
        if (tablePengiriman.getColumnModel().getColumnCount() > 0) {
            tablePengiriman.getColumnModel().getColumn(0).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(1).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(2).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(3).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(4).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(5).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(6).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(7).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(8).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(10).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(11).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(12).setResizable(false);
            tablePengiriman.getColumnModel().getColumn(14).setResizable(false);
        }

        btnTemplate.setText("Template Excel");
        btnTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemplateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTemplate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnTemplate)
                    .addComponent(btnSave))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePengirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePengirimanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePengirimanMouseClicked

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "Selected file: " + selectedFile.getAbsolutePath());
            Excel test = new Excel();
            test.inputFile = (String)selectedFile.getAbsolutePath();
            try {
                hasilImport=test.fromExcel();
                if(hasilImport!=null){
                int baris = hasilImport.length;
                int tempSwitch=0;
                String namaPengirim="";
                String namaPenerima="";
                String idKecPengirim="";
                String idKecPenerima="";
                String alamatPenerima="";
                String tanggalInput="";
                String tanggalKirim="";
                String tanggalTiba="";
                String total="";
                String idLayanan="";
                String idKurir="";
                String hargaPengiriman="";
                String hariPengiriman="";
                String verifikasiPengiriman="";
                String ketBarang="";
                String beratBarang="";
                for(int i=0;i<baris;i++){
                    if(i!=0){
                        if(hasilImport[i].length==16){
                            
                        for(int j=0;j<hasilImport[i].length;j++){
                            if(j==0){
                                namaPengirim=hasilImport[i][j];
                            }

                            if(j==1){
                                namaPenerima=hasilImport[i][j];
                            }
                            
                            if(j==2){
                                idKecPengirim=hasilImport[i][j];
                            }
                            
                            if(j==3){
                                idKecPenerima=hasilImport[i][j];
                            }
                            
                            
                            if(j==4){
                                alamatPenerima=hasilImport[i][j];
                            }
                            
                            if(j==5){
                                tanggalInput=hasilImport[i][j];
                            }
                            
                            if(j==6){
                                tanggalKirim=hasilImport[i][j];
                            }
                            
                            if(j==7){
                                tanggalTiba=hasilImport[i][j];
                            }
                            
                            if(j==8){
                                total=hasilImport[i][j];
                            }
                            
                            if(j==9){
                                idLayanan=hasilImport[i][j];
                            }
                            
                            if(j==10){
                                idKurir=hasilImport[i][j];
                            }
                            
                            if(j==11){
                                hargaPengiriman=hasilImport[i][j];
                            }
                            
                            if(j==12){
                                hariPengiriman=hasilImport[i][j];
                            }
                            
                            if(j==13){
                                verifikasiPengiriman=hasilImport[i][j];
                            }
                            
                            if(j==14){
                                ketBarang=hasilImport[i][j];
                            }
                            
                            if(j==15){
                                beratBarang=hasilImport[i][j];
                            }
                        
                        }
                        
                        model.addRow(new Object[]{namaPengirim, namaPenerima, idKecPengirim, idKecPenerima, alamatPenerima, tanggalInput, tanggalKirim, tanggalTiba, total, idLayanan, idKurir, hargaPengiriman, hariPengiriman, verifikasiPengiriman, ketBarang, beratBarang});
                        tempSwitch=1;
                        }else{
                            JOptionPane.showMessageDialog(this, "Harus ada data dan sesuai dengan format template");
                            break;
                        }
                    }
                }

                if(tempSwitch>=1){
                    btnSave.setEnabled(true);
                }
                }

            } catch (IOException ex) {
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Harus ada data dan sesuai dengan format template");
            }
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int baris = hasilImport.length;
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date date = new Date();
                String dateNow = (String)dateFormat.format(date);
                String tanggalTemp="";
                String idPengiriman="";
                String namaPengirim="";
                String namaPenerima="";
                String idKecPengirim="";
                String idKecPenerima="";
                String alamatPenerima="";
                String tanggalInput="";
                String tanggalKirim="";
                String tanggalTiba="";
                int total=0;
                String idLayanan="";
                String idKurir="";
                int hargaPengiriman=0;
                String hariPengiriman="";
                String verifikasiPengiriman="";
                String ketBarang="";
                String beratBarang="";

        for(int i=0;i<baris;i++){
            for(int j=0;j<hasilImport[i].length;j++){
                if(i!=0){
                            if(j==0){
                                namaPengirim=hasilImport[i][j];
                            }

                            if(j==1){
                                namaPenerima=hasilImport[i][j];
                            }
                            
                            if(j==2){
                                idKecPengirim=hasilImport[i][j];
                            }
                            
                            if(j==3){
                                idKecPenerima=hasilImport[i][j];
                            }
                            
                            
                            if(j==4){
                                alamatPenerima=hasilImport[i][j];
                            }
                            
                            if(j==5){
                                if(hasilImport[i][j]!=""){
                                    tanggalInput=hasilImport[i][j];
                                }else{
                                    tanggalInput="";
                                }
                            }
                            
                            if(j==6){
                                tanggalKirim=hasilImport[i][j];
                            }
                            
                            if(j==7){
                                tanggalTiba=hasilImport[i][j];
                            }
                            
                            if(j==8){
                                if(hasilImport[i][j]!=""){
                                total=Integer.parseInt(hasilImport[i][j]);
                                }
                            }
                            
                            if(j==9){
                                idLayanan=hasilImport[i][j];
                            }
                            
                            if(j==10){
                                idKurir=hasilImport[i][j];
                            }
                            
                            if(j==11){
                                if(hasilImport[i][j]!=""){
                                hargaPengiriman=Integer.parseInt(hasilImport[i][j]);
                                }
                            }
                            
                            if(j==12){
                                hariPengiriman=hasilImport[i][j];
                            }
                            
                            if(j==13){
                                verifikasiPengiriman=hasilImport[i][j];
                            }
                            
                            if(j==14){
                                ketBarang=hasilImport[i][j];
                            }
                            
                            if(j==15){
                                beratBarang=hasilImport[i][j];
                            }
                 
                }

            }
            if(i!=0){
                if(namaPengirim!=""){
                    tanggalTemp = tanggalInput;
                    pengiriman.setPengiriman(namaPengirim, namaPenerima, idKecPengirim, idKecPenerima, alamatPenerima, tanggalInput, tanggalKirim, tanggalTiba, total, idLayanan, idKurir, hargaPengiriman, hariPengiriman);
                    idPengiriman = (String) pengiriman.getPengirimanbyDatetime(tanggalTemp).get(0).get(0);
                    pengiriman.setBarang(idPengiriman, ketBarang, beratBarang);  
                }else{
                    idPengiriman = (String) pengiriman.getPengirimanbyDatetime(tanggalTemp).get(0).get(0);
                    pengiriman.setBarang(idPengiriman, ketBarang, beratBarang);
                }
            }
        }

        if(baris>1){
            JOptionPane.showMessageDialog(this, "Berhasil import pengiriman");
            btnSave.setEnabled(false);
            model= (DefaultTableModel) tablePengiriman.getModel();
            model.getDataVector().removeAllElements();
            revalidate();
        }else{
            JOptionPane.showMessageDialog(this, "Harus ada data dan sesuai dengan format template");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemplateActionPerformed
        // TODO add your handling code here:
        try {
            Excel excel = new Excel();
            File source = new File("src/excel template/Pengiriman.xls");
            File dest;

            JFileChooser fc = new JFileChooser();
            int option = fc.showSaveDialog(com.espada.gui.excel.importz.Pengiriman.this);
            if(option == JFileChooser.APPROVE_OPTION){
                String filename = fc.getSelectedFile().getName();
                String path = fc.getSelectedFile().getParentFile().getPath();

                int len = filename.length();
                String ext = "";
                String file = "";

                if(len > 4){
                    ext = filename.substring(len-4, len);
                }

                if(ext.equals(".xls")){
                    file = path + "\\" + filename; 
                }else{
                    file = path + "\\" + filename + ".xls"; 
                }

                dest = new File(file);

                excel.getTemplate(source, dest);
            }
        } catch (IOException ex) {
            Logger.getLogger(Kurir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTemplateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengiriman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTemplate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePengiriman;
    // End of variables declaration//GEN-END:variables
}
